// Generated by tools/generate_esphome_catalog.py; do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace esphome::huawei_emma_reverse {

enum class GeneratedValueType : uint8_t { U16, U32, I32, TOU };

struct GeneratedEntityMetadata {
  const char *register_name;
  const char *esphome_id;
  const char *name;
  uint16_t address;
  uint16_t length;
  const char *platform;
  const char *poll_group;
  const char *device_role;
  const char *client_role;
  const char *unit;
  const char *device_class;
  const char *state_class;
  const char *entity_category;
  const char *icon;
  bool enabled_default;
  bool writeable;
  const char *format;
  GeneratedValueType value_type;
  double gain;
};

inline constexpr char GENERATED_CATALOG_SHA256[] = "c22e47798c651b35a65e11735b18dcff03c4493728621beb7ff174a1e82d9758";
inline constexpr uint16_t GENERATED_CORE_ADDRESS = 30354;
inline constexpr uint16_t GENERATED_CORE_COUNT = 20;
inline constexpr size_t GENERATED_CORE_ENTITY_COUNT = 10;
inline constexpr size_t GENERATED_ENTITY_COUNT = 11;

inline constexpr std::array<GeneratedEntityMetadata, GENERATED_ENTITY_COUNT>
    GENERATED_ENTITIES{{
        {"pv_output_power", "emma_pv_output_power", "PV Output Power", 30354, 2, "sensor", "fast", "emma", "emma", "W", "power", "measurement", "", "mdi:solar-power", true, false, "", GeneratedValueType::U32, 1},
        {"load_power", "emma_load_power", "Load Power", 30356, 2, "sensor", "fast", "emma", "emma", "W", "power", "measurement", "", "mdi:home-lightning-bolt", true, false, "", GeneratedValueType::U32, 1},
        {"feed_in_power", "emma_feed_in_power", "Feed In Power", 30358, 2, "sensor", "fast", "emma", "emma", "W", "power", "measurement", "", "mdi:transmission-tower", true, false, "", GeneratedValueType::I32, 1},
        {"battery_charge_discharge_power", "emma_battery_charge_discharge_power", "Battery Charge Discharge Power", 30360, 2, "sensor", "fast", "emma", "emma", "W", "power", "measurement", "", "mdi:battery", true, false, "", GeneratedValueType::I32, 1},
        {"inverter_rated_power", "emma_inverter_rated_power", "Inverter Rated Power", 30362, 2, "sensor", "slow", "inverter", "emma", "W", "power", "measurement", "", "", true, false, "", GeneratedValueType::U32, 1},
        {"inverter_active_power", "emma_inverter_active_power", "Inverter ACtive Power", 30364, 2, "sensor", "fast", "inverter", "emma", "W", "power", "measurement", "", "", true, false, "", GeneratedValueType::I32, 1},
        {"state_of_capacity", "emma_state_of_capacity", "State Of Capacity", 30368, 1, "sensor", "medium", "emma", "emma", "%", "battery", "measurement", "", "mdi:list-status", true, false, "", GeneratedValueType::U16, 100},
        {"ess_chargeable_capacity", "emma_ess_chargeable_capacity", "ESS Chargeable Capacity", 30369, 2, "sensor", "medium", "emma", "emma", "kWh", "energy_storage", "measurement", "", "mdi:battery", true, false, "", GeneratedValueType::U32, 1000},
        {"ess_dischargeable_capacity", "emma_ess_dischargeable_capacity", "ESS Dischargeable Capacity", 30371, 2, "sensor", "medium", "emma", "emma", "kWh", "energy_storage", "measurement", "", "mdi:battery", true, false, "", GeneratedValueType::U32, 1000},
        {"backup_power_state_of_charge", "emma_backup_power_state_of_charge", "Backup Power State Of Charge", 30373, 1, "sensor", "fast", "smartguard", "emma", "%", "battery", "measurement", "", "mdi:list-status", true, false, "", GeneratedValueType::U16, 100},
        {"emma_tou_periods", "emma_emma_tou_periods", "EMMA TOU Periods", 40004, 43, "sensor", "medium", "emma", "emma", "", "", "", "diagnostic", "mdi:calendar-clock", false, true, "tou_periods", GeneratedValueType::TOU, 1},
    }};

}  // namespace esphome::huawei_emma_reverse
