#!/usr/bin/env python3
"""Generate ESPHome register metadata from the canonical Python catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from emma_catalog import VIRTUAL_ENTITY_DESCRIPTIONS, build_entity_catalog
from huawei_solar.registers import REGISTERS


CORE_REGISTER_NAMES = (
    "pv_output_power",
    "load_power",
    "feed_in_power",
    "battery_charge_discharge_power",
    "inverter_rated_power",
    "inverter_active_power",
    "state_of_capacity",
    "ess_chargeable_capacity",
    "ess_dischargeable_capacity",
    "backup_power_state_of_charge",
)
STRUCTURED_REGISTER_NAMES = ("emma_tou_periods",)
FIRMWARE_REGISTER_NAMES = CORE_REGISTER_NAMES + STRUCTURED_REGISTER_NAMES

DEFAULT_HEADER = ROOT / "esphome/components/huawei_emma_reverse/generated_register_catalog.h"
DEFAULT_MANIFEST = ROOT / "esphome/entity-migration-map.json"


def _esphome_id(register_name: str) -> str:
    value = re.sub(r"[^a-z0-9_]+", "_", register_name.lower()).strip("_")
    return f"emma_{value}"


def _entry(description: dict[str, Any], *, virtual: bool) -> dict[str, Any]:
    register_name = str(description["register_name"])
    result = dict(description)
    if isinstance(result.get("options"), tuple):
        result["options"] = list(result["options"])
    result.update(
        {
            "logical_id": register_name,
            "esphome_id": _esphome_id(register_name),
            "hacs_unique_id_template": f"{{emma_serial}}_{register_name}",
            "entity_owner": "huawei_emma_management",
            "firmware_supported": register_name in FIRMWARE_REGISTER_NAMES,
            "virtual": virtual,
        }
    )
    return result


def build_manifest() -> dict[str, Any]:
    catalog = build_entity_catalog()
    physical = [
        _entry(description.to_dict(), virtual=False)
        for description in sorted(
            catalog.values(), key=lambda item: (item.address, item.register_name)
        )
    ]
    virtual = [
        _entry(dict(description), virtual=True)
        for description in VIRTUAL_ENTITY_DESCRIPTIONS.values()
    ]
    entities = physical + virtual
    canonical = json.dumps(entities, sort_keys=True, separators=(",", ":"))
    return {
        "schema_version": 1,
        "catalog_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
        "source": {
            "python_module": "custom_components.huawei_emma_management.embedded_catalog",
            "register_library": "huawei-solar==3.0.6",
            "generator": "tools/generate_esphome_catalog.py",
        },
        "entity_policy": {
            "owner": "huawei_emma_management",
            "logical_id": "register_name",
            "hacs_unique_id": "{emma_serial}_{register_name}",
            "esphome_id": "emma_{register_name}",
            "migration": (
                "Keep the HACS integration as entity owner and change only its external "
                "connector host; existing entity-registry IDs remain unchanged."
            ),
        },
        "physical_entity_count": len(physical),
        "virtual_entity_count": len(virtual),
        "firmware_supported_count": len(FIRMWARE_REGISTER_NAMES),
        "entities": entities,
    }


def _cpp_string(value: Any) -> str:
    if value is None:
        value = ""
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _value_type(register_name: str) -> str:
    class_name = type(REGISTERS[register_name]).__name__
    if class_name == "U16Register":
        return "GeneratedValueType::U16"
    if class_name == "U32Register":
        return "GeneratedValueType::U32"
    if class_name == "I32Register":
        return "GeneratedValueType::I32"
    if class_name == "HUAWEI_LUNA2000_TimeOfUseRegisters":
        return "GeneratedValueType::TOU"
    raise ValueError(f"Unsupported firmware register type {class_name}: {register_name}")


def build_header(manifest: dict[str, Any]) -> str:
    descriptions = build_entity_catalog()
    core_start = min(descriptions[name].address for name in CORE_REGISTER_NAMES)
    core_end = max(
        descriptions[name].address + descriptions[name].length
        for name in CORE_REGISTER_NAMES
    )
    lines = [
        "// Generated by tools/generate_esphome_catalog.py; do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace esphome::huawei_emma_reverse {",
        "",
        "enum class GeneratedValueType : uint8_t { U16, U32, I32, TOU };",
        "",
        "struct GeneratedEntityMetadata {",
        "  const char *register_name;",
        "  const char *esphome_id;",
        "  const char *name;",
        "  uint16_t address;",
        "  uint16_t length;",
        "  const char *platform;",
        "  const char *poll_group;",
        "  const char *device_role;",
        "  const char *client_role;",
        "  const char *unit;",
        "  const char *device_class;",
        "  const char *state_class;",
        "  const char *entity_category;",
        "  const char *icon;",
        "  bool enabled_default;",
        "  bool writeable;",
        "  const char *format;",
        "  GeneratedValueType value_type;",
        "  double gain;",
        "};",
        "",
        f'inline constexpr char GENERATED_CATALOG_SHA256[] = "{manifest["catalog_sha256"]}";',
        f"inline constexpr uint16_t GENERATED_CORE_ADDRESS = {core_start};",
        f"inline constexpr uint16_t GENERATED_CORE_COUNT = {core_end - core_start};",
        f"inline constexpr size_t GENERATED_CORE_ENTITY_COUNT = {len(CORE_REGISTER_NAMES)};",
        f"inline constexpr size_t GENERATED_ENTITY_COUNT = {len(FIRMWARE_REGISTER_NAMES)};",
        "",
        "inline constexpr std::array<GeneratedEntityMetadata, GENERATED_ENTITY_COUNT>",
        "    GENERATED_ENTITIES{{",
    ]
    for register_name in FIRMWARE_REGISTER_NAMES:
        description = descriptions[register_name]
        register = REGISTERS[register_name]
        gain = float(getattr(register, "gain", 1))
        fields = (
            _cpp_string(register_name),
            _cpp_string(_esphome_id(register_name)),
            _cpp_string(description.name),
            str(description.address),
            str(description.length),
            _cpp_string(description.platform),
            _cpp_string(description.poll_group),
            _cpp_string(description.device_role),
            _cpp_string(description.client_role),
            _cpp_string(description.unit),
            _cpp_string(description.device_class),
            _cpp_string(description.state_class),
            _cpp_string(description.entity_category),
            _cpp_string(description.icon),
            "true" if description.enabled_default else "false",
            "true" if description.writeable else "false",
            _cpp_string(description.format),
            _value_type(register_name),
            f"{gain:.12g}",
        )
        lines.append("        {" + ", ".join(fields) + "},")
    lines.extend(["    }};", "", "}  // namespace esphome::huawei_emma_reverse", ""])
    return "\n".join(lines)


def generated_outputs() -> dict[Path, str]:
    manifest = build_manifest()
    return {
        DEFAULT_MANIFEST: json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        DEFAULT_HEADER: build_header(manifest),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in generated files differ from the Python catalog",
    )
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in generated_outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"Generated {path.relative_to(ROOT)}")
    if stale:
        joined = ", ".join(str(path) for path in stale)
        raise SystemExit(
            f"ESPHome catalog artifacts are stale: {joined}. "
            "Run python tools/generate_esphome_catalog.py"
        )


if __name__ == "__main__":
    main()
